from __future__ import annotations

import datetime as dt
from pathlib import Path

import httpx

from djx.clients.spotify import SpotifyClient
from djx.recommender.score import ScoredTrack


def playlist_name(today: dt.date | None = None) -> str:
    today = today or dt.date.today()
    return f"X + Spotify Hybrid Vibes - {today.isoformat()}"


def playlist_description(num_seeds: int, num_tweets: int, mood: str, energy: str) -> str:
    return (
        f"Auto-generated by dj-x-supercharged. "
        f"Seeded by {num_seeds} top artists + {num_tweets} analyzed tweets. "
        f"Dominant mood: {mood}, energy: {energy}."
    )


async def build_playlist(
    spotify: SpotifyClient,
    user_id: str,
    tracks: list[ScoredTrack],
    *,
    name: str | None = None,
    description: str = "",
    public: bool = False,
    dry_run: bool = False,
) -> dict:
    final_name = name or playlist_name()
    if dry_run:
        return {
            "dry_run": True,
            "name": final_name,
            "description": description,
            "tracks": [
                {"name": s.candidate.name, "artist": s.candidate.artist_name, "score": s.score}
                for s in tracks
            ],
        }
    try:
        playlist = await spotify.create_playlist(
            user_id=user_id, name=final_name, description=description, public=public
        )
    except httpx.HTTPStatusError as e:
        if e.response.status_code == 403:
            return _degraded_response(final_name, description, tracks, reason="spotify_403")
        raise
    uris = [s.candidate.uri for s in tracks]
    await spotify.add_tracks(playlist["id"], uris)
    return {
        "dry_run": False,
        "degraded": False,
        "id": playlist["id"],
        "url": playlist.get("external_urls", {}).get("spotify"),
        "name": final_name,
        "track_count": len(uris),
    }


def _degraded_response(
    name: str, description: str, tracks: list[ScoredTrack], *, reason: str
) -> dict:
    """Spotify rejected the create call (commonly: dev-mode user not whitelisted).
    Write the URIs to a file the user can paste into Spotify, and return a
    structured response so the CLI can print clear next steps.
    """
    out_dir = Path("~/.djx/exports").expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    safe = name.replace("/", "-").replace(" ", "_")
    txt = out_dir / f"{dt.datetime.now():%Y%m%d_%H%M%S}_{safe}.txt"
    lines = [
        f"# {name}",
        f"# {description}",
        "",
        "# To preview: open Spotify, create a new playlist, and paste these track URIs:",
        "",
    ]
    lines.extend(s.candidate.uri for s in tracks)
    txt.write_text("\n".join(lines), encoding="utf-8")
    return {
        "dry_run": False,
        "degraded": True,
        "reason": reason,
        "name": name,
        "description": description,
        "track_count": len(tracks),
        "uris_file": str(txt),
        "tracks": [
            {
                "name": s.candidate.name,
                "artist": s.candidate.artist_name,
                "score": s.score,
                "uri": s.candidate.uri,
            }
            for s in tracks
        ],
    }
